version: '3.7'
services:

  sftp-windows:
    image: emberstack/sftp
    profiles:
      - windows
    # volumes:
    #   - ./data/sftp.json:/app/config/sftp.json:ro
    #   - ./data/sftpdata:/home/demo/sftp
    ports:
      - "2222:22"

  sftp-unix:
    image: atmoz/sftp:latest
    profiles:
      - unix
    ports:
      - "2222:22"
    volumes:
      - "./testdata/outbox:/home/demo/outbox"
      - "./testdata/bigdata:/home/demo/bigdata"
      - "./testdata/root.txt:/home/demo/root.txt"
    command:
      - "demo:password:::outbox,upload"
