name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    # - name: Install Docker Desktop
    #   if: runner.os == 'Windows'
    #   run: |
    #     choco install docker-desktop

    # - name: Switch to Linux Containers
    #   if: runner.os == 'Windows'
    #   # Tips from https://stackoverflow.com/a/57081502
    #   run: |
    #     C:\"Program Files"\Docker\Docker\DockerCli.exe -SwitchLinuxEngine

    #     Stop-Service -Name Docker
    #     Start-Service -Name Docker

    #     docker version

    - name: Setup
      run: make setup

    - name: Check
      run: make check

    - name: Teardown
      if: ${{ always() }}
      run: make teardown
